

name: Trigger dbt cloud job to prep views and build docs
on:
  {trigger}

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    steps:
    - name: Run dbt cloud job
      run: |
        RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBTCLOUDAPIKEY }}" -H "Content-Type:application/json" -d '{"cause":"Triggered by Github Actions","git_branch":"${{ github.head_ref || github.ref_name }}"}' {dbt_cloud_api_run_url})
        STATUSCODE=$(echo "$RESPONSE" | jq '.status.code')
        echo "$RESPONSE" | jq '.status.user_message'
        if [[ $STATUSCODE != 200 ]]; then echo "$RESPONSE" && bash -c "exit 1"; fi
        RUN_ID=$(echo "$RESPONSE" | jq '.data.id')
        RUN_RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBTCLOUDAPIKEY }}" https://cloud.getdbt.com/api/v2/accounts/1713/runs/"$RUN_ID"/)
        RUN_STATUS=$(echo "$RUN_RESPONSE" | jq '.data.status_humanized' | xargs)
        echo "RUN STATUS: $RUN_STATUS"
        while [[ "$RUN_STATUS" == "Queued" || "$RUN_STATUS" == "Starting" || "$RUN_STATUS" == "Running" ]]
        do
            sleep 10
            RUN_RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBTCLOUDAPIKEY }}" https://cloud.getdbt.com/api/v2/accounts/1713/runs/"$RUN_ID"/)
            RUN_STATUS=$(echo "$RUN_RESPONSE" | jq '.data.status_humanized' | xargs)
            echo "RUN STATUS: $RUN_STATUS"
        done
        if [[ "$RUN_STATUS" == "Error" || "$RUN_STATUS" == "Cancelled" ]]; then echo "$RESPONSE" && bash -c "exit 1"; fi
        echo "RUN STATUS: $RUN_STATUS"
