---
version: 2
macros:
  - name: create_mart_combined_email_paidmedia_daily_revenue_performance
    description: 
    arguments:
      - name: reference_0_name
        type: string
        description: the name of the email model
      - name: reference_1_name
        type: string
        description: the name of the paidmedia model
  - name: create_mart_paidmedia_daily_revenue_performance
    description: 
    arguments:
      - name: campaigns
      - name: impressions
      - name: clicks
      - name: spends
      - name: transactions
      - name: subscribes
  - name: create_mart_email_listhealth_by_month
    description: 
    arguments:
      - name: reference_name
        type: string
        description: staging table that pulls from mart_email_performance_with_revenue
  - name: create_mart_email_deliverability_by_domain_and_date
    description: 
    arguments:
      - name: jobs
      - name: details
      - name: bounces
      - name: clicks
      - name: opens
      - name: actions
      - name: recipients
      - name: transactions
      - name: unsubscribes
  - name: create_mart_paidmedia_monthly_goals_and_actuals
    description: 
