version: 2

macros:
  - name: create_mart_combined_email_paidmedia_daily_revenue_performance
    description: a macro that unions two tables
    arguments:
      - name: reference_0_name
        type: string
        description: the name of the email model
      - name: reference_1_name
        type: string
        description: the name of the paidmedia model
  - name: create_mart_email_performance_with_revenue
    description: a macro that builds the ARC email reporting table 
    arguments:
      - name: jobs
      - name: campaigns
      - name: campaign_dates
      - name: bounces
      - name: clicks
      - name: opens
      - name: actions
      - name: recipients
      - name: transactions
      - name: unsubscribes

models:
  - name: mart_combined_email_paidmedia_daily_revenue_performance
    description: a model that unions the mart_paidmedia model and the mart_email model
    columns:
      - name: channel
        description: bot name from frakture
      - name: best_guess_entity
        description: > 
          concatenates the bot label and the entity-related source code together. 
          aim is to identify multiple accounts from the same channel.
      - name: total_revenue
        description: sum of all revenue
      - name: total_gifts
        description: count of transactions
  - name: mart_email_performance_with_revenue
    description: a model that rolls up email performance KPIs by email name, showing a date
    columns:
      - name: message_id
        description: frakture ID that is unique to each creative, but not unique to each row
      - name: from_name
        description: the name of the person or entity that sent the email
      - name: from_email
        description: the name of the email address that sent the email
      - name: best_guess_timestamp
        description: the best guess timestamp for a sent date (use this one)        
      - name: scheduled_timestamp
        description: the time an email was scheduled to be sent
      - name: pickup_timestamp
        description:
      - name: delivered_timestamp
        description: the time an email was delivered
      - name: campaign_start_timestamp
        description:  the timestamp of the earliest email sent in a campaign      
      - name: campaign_latest_timestamp
        description: the timestamp of the latest email sent in a campaign
      - name: email_name
        description: label name of the email
      - name: email_subject
        description: email subject line
      - name: source_code
        description: email source code       
      - name: crm_entity
        description: account name, for example facebook 1, facebook 2
      - name: source_code_entity
        description: parsed segment of frakture source code field "entity"
      - name: best_guess_entity
        description: concatenation of crm_entity and source_code entity
      - name: audience
        description: parsed segment of frakture source code field "audience"
      - name: campaign_category
        description: parsed segment of frakture source code field "message_set"
      - name: campaign_name
        description: coalesce of campaign name field from CRM or parsed segment of frakture source code field "campaign"
      - name: recurtype
        description: parsed segment of frakture source code field "recurtype"; a flag for triggered vs bulk email
      - name: recipients
        description: count of email total sends        
      - name: opens
        description: count of email total opens
      - name: clicks
        description: count of email total clicks
      - name: actions
        description: > 
          count of email total actions 
          in Actionkit, count of entries in core_action table
          minus donations, unsubscribe, and incompletes
          in EveryAction, FormSubmissionCount; 
          in EngagingNetworks, Advocacy Count
      - name: total_bounces
        description: count of total bounces        
      - name: block_bounces
        description:
      - name: tech_bounces
        description:
      - name: soft_bounces
        description:
      - name: unknown_bounces
        description:        
      - name: unsubscribes
        description: count of unsubscribes
      - name: total_revenue
        description: sum of total_revenue
      - name: total_gifts
        description: count of transactions
      - name: total_donors
        description: count of unique donors using origin person ID    
      - name: one_time_revenue
        description: sum of one time revenue
      - name: one_time_gifts
        description: count of one time transactions
      - name: new_monthly_revenue
        description: sum of initial recurring revenue
      - name: new_monthly_gifts
        description: count of intial recurring transactions
      - name: total_monthly_revenue
        description: sum of total recurring revenue
      - name: total_monthly_gifts
        description: count of total recurring transactions
