SELECT date_day,
 interval_type,
 donor_audience,
 platform,
 total_recur_donor_counts,
 new_recur_donor_counts,
 retained_recur_donor_counts,
 retained3_recur_donor_counts,
 active_recur_donor_counts,
 lapsed_recur_donor_counts,
FROM {{ ref ('recur_donor_counts_daily')}}
UNION ALL
SELECT date_day,
 interval_type,
 donor_audience,
 platform,
 total_recur_donor_counts,
 new_recur_donor_counts,
 retained_recur_donor_counts,
 retained3_recur_donor_counts,
 active_recur_donor_counts,
 lapsed_recur_donor_counts,
FROM {{ ref ('recur_donor_counts_monthly')}}
UNION ALL
SELECT date_day,
 interval_type,
 donor_audience,
 platform,
 total_recur_donor_counts,
 new_recur_donor_counts,
 retained_recur_donor_counts,
 retained3_recur_donor_counts,
 active_recur_donor_counts,
 lapsed_recur_donor_counts,
FROM {{ ref ('recur_donor_counts_yearly')}}