---
name: Check for properly formatted macros and docs
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  check_formatted_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pyyaml
      - name: Check macros are formatted correctly
        run: |
          cd utils
          ./check_macros.py
      - name: Check for well formatted docs and that macros exist for docs
        run: |-
          cd utils
          ./check_docs_correct.py
