---
name: black-action
on: 
  pull_request:
jobs:
  python_black:
    if: startsWith(github.head_ref, 'actions/action_black') == false && github.event.pull_request.head.repo.full_name == github.repository
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: .
      - name: Create Pull Request
        if: ${{ steps.action_black.outputs.is_formatted }} == true
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
          branch: actions/action_black/${{ github.ref_name || github.head_ref }}
          title: Python Black to ${{ github.ref_name || github.head_ref }}
          base: ${{ github.head_ref }}
      - name: Fail if action_black is_formatted
        if: ${{ steps.action_black.outputs.is_formatted }} == true && [[ ${{ github.ref_name || github.head_ref }} != *"actions/action_black"* ]]
        run: exit 1
