---
name: Lint YAML
on:
  pull_request:
permissions:
  contents: read
jobs:
  build:
    if: startsWith(github.head_ref, 'actions/yamlfix') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}/actions/yamlfix
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install yamlfix
      - name: yamlfix
        run: |-
          YAMLFIX_OUTPUT=$(yamlfix . 2>&1)
          if [[ $YAMLFIX_OUTPUT != *" 0 fixed"* ]]; then
            echo "Run yamlfix . to fix the errors below"
            echo $YAMLFIX_OUTPUT
            echo "is_formatted=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_formatted=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: ${{ steps.yamlfix.outputs.is_formatted }} == true
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHA_PERSONAL_ACCESS_TOKEN }}
          branch: actions/yamlfix/${{ github.ref_name || github.head_ref }}
          title: YamlFix to ${{ github.ref_name || github.head_ref }}
      - name: Fail if yamlfix is_formatted
        if: ${{ steps.yamlfix.outputs.is_formatted }} == true && [[ ${{ github.ref_name || github.head_ref }}
          != *"actions/yamlfix"* ]]
        run: exit 1
