---
name: Lint YAML
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}/actions/yamlfix
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install yamlfix
      - name: yamlfix
        run: |-
          YAMLFIX_OUTPUT=$(yamlfix . 2>&1)
          if [[ $YAMLFIX_OUTPUT != *" 0 fixed"* ]]; then
            echo "Run yamlfix . to fix the errors below"
            echo $YAMLFIX_OUTPUT
            echo "is_formatted=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_formatted=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: ${{ steps.yamlfix.outputs.is_formatted }} == true
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Format Yaml code with yamlfix push
          commit-message: ':art: Format Yaml code with yamlfix'
          body: |
            There appear to be some yaml formatting errors in ${{ github.sha }}. This pull request
            uses the [yamlfix](https://lyz-code.github.io/yamlfix/) formatter to fix these issues.
          base: ${{ github.head_ref }}  # Creates pull request onto pull request or commit branch
          branch: actions/yamlfix
